### ISSUE TITLE
Send a notification to the reviewers if the PR gets updated

### ISSUE THREAD

**Issue by DannyFeliz** [DannyFeliz/Dashi#24]
Notes: 
* You should enable the `push` webhook to archive this
* Only pull requests with an open state should trigger the notification

**Comment by duckoder** [comment]
@DannyFeliz hello, I can help you with this

**Comment by DannyFeliz** [comment]
Hi @zhikiri go ahead man

**Comment by duckoder** [comment]
@DannyFeliz Sorry, I don't have time for this task right now :(

**Comment by DannyFeliz** [comment]
@zhikiri Ok, I will take this one
