### ISSUE TITLE
Setup the mail configuration in production

### ISSUE THREAD

**Issue by DannyFeliz** [DannyFeliz/Dashi#29]
We need this to be able to send emails such as the `Forgot Your Password`

**Comment by dercodercom** [comment]
Forgot Your Password is a Standard Function from Laravel and exist in this Application, i tested the function.

**Comment by DannyFeliz** [comment]
@dercodercom yeah, I already implemented this function in other application what I going to do is just setup everything in this project.

**Comment by dercodercom** [comment]
@DannyFeliz i have installed this project locally and tested the application without problems.

**Comment by DannyFeliz** [comment]
@dercodercom you are right man, I set the wrong title to this issue, what I mean is setup the mail in production because the .env file doesn't have the mail credentials.
