### ISSUE TITLE
Add a guide to demonstrate how to set up the project locally 

### ISSUE THREAD

**Issue by DannyFeliz** [DannyFeliz/Dashi#31]

**Comment by dongido001** [comment]
Hi @DannyFeliz , I'm interested in this :D

**Comment by DannyFeliz** [comment]
@dongido001 go ahead!

**Comment by leninpaulino** [comment]
@dongido001  are you working on this? I'm gonna take this one.

**Comment by dongido001** [comment]
Hey, carry on. Been busy

**Comment by leninpaulino** [comment]
@DannyFeliz done. PR is waiting for review.

**Comment by DannyFeliz** [comment]
Resolved by #45
