### ISSUE TITLE
Send a notification when a pull request is merged

### ISSUE THREAD

**Issue by DannyFeliz** [DannyFeliz/Dashi#35]
Note: Make this feature configurable through a checkbox in the config page

**Comment by adioe3** [comment]
I'd like to take this one

**Comment by DannyFeliz** [comment]
@adioe3 Excellent :D

**Comment by leninpaulino** [comment]
@adioe3  do you still work on this? I'm gonna take it.

**Comment by DannyFeliz** [comment]
@adioe3 seems to be busy @lepau take it
