### ISSUE TITLE
When a PR is merged sends a notification as rejected

### ISSUE THREAD

**Issue by DannyFeliz** [DannyFeliz/Dashi#84]
Consider check the fields:
```
"action": "closed",
"merged": true,
"merged_by": null
```
in order to check if the PR was closed explicitly or merged

**Comment by gabbanaesteban** [comment]
![bug](https://user-images.githubusercontent.com/11374198/34847301-483f31fc-f6f1-11e7-9b59-9e2f7885bb38.png)
