### ISSUE TITLE
The request change notification display the wrong author text

### ISSUE THREAD

**Issue by DannyFeliz** [DannyFeliz/Dashi#86]
The PR owner is @DannyFeliz08 and who requested the changes is @gabbanaesteban, so this notification should be displaying **DannyFeliz** instead of gabbanaesteban
![screen shot 2018-01-11 at 4 44 07 pm](https://user-images.githubusercontent.com/5460365/34847097-a04733be-f6f0-11e7-994a-22cb69237cf5.png)

**Comment by gabbanaesteban** [comment]
Fix in #95
